# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# Versions of PHP to test against
php:
#    - "5.6"
    - "7.0"
#    - "7.1"

# Specify versions of WordPress to test against
# WP_VERSION = WordPress version number (use "master" for SVN trunk)
# WP_MULTISITE = whether to test multisite (use either "0" or "1")
env:
    - WP_VERSION=master WP_MULTISITE=0
 #   - WP_VERSION=4.8.1 WP_MULTISITE=0
 #   - WP_VERSION=master WP_MULTISITE=1
 #   - WP_VERSION=4.8.1 WP_MULTISITE=1

before_script:
    # Grab the setup script and execute
    - export PLUGIN_SLUG=$(basename $(pwd))
    - sudo git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /var/www
    - cd ..
    - sudo mv "$PLUGIN_SLUG" "/var/www/src/wp-content/plugins/$PLUGIN_SLUG"
    - cd /var/www
    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    - sudo cp wp-tests-config-sample.php wp-tests-config.php
    - sudo sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
    - sudo sed -i "s/yourusernamehere/travis/" wp-tests-config.php
    - sudo sed -i "s/yourpasswordhere//" wp-tests-config.php
    # Disable Wp Debug (Not to Show notice etc...) 
    - sudo sed -i "s/WP_DEBUG/WP_NO_DEBUG/" wp-tests-config.php
    - sudo chmod 777 /var/www/src -Rf
    
    # Move to Plugin Dir
    - cd "/var/www/src/wp-content/plugins/$PLUGIN_SLUG"

    # Installl Apache2 & Php-Fpm
    - sudo apt-get update
    - sudo apt-get install apache2 libapache2-mod-fastcgi
    
    # enable php-fpm    
    - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf; fi
    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
    - sudo a2enmod rewrite actions fastcgi alias
    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
    
    # Configure Apache virtual hosts
    - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?/var/www/src?g" --in-place /etc/apache2/sites-available/default
    - sudo service apache2 restart
    - cat /etc/apache2/sites-available/default
    - ll /var/www
    - ll /etc/apache2/sites-enabled
    
    # Run Composer
    - composer update 
    - pwd
    - curl -sL -w "%{http_code}\\n" "http://127.0.0.1" 
    - curl -sL -w "%{http_code}\\n" "http://127.0.0.1/src" 
    - curl -sL -w "%{http_code}\\n" "http://127.0.0.1/src/wp-content/plugins/Wordpress/vendor/splash/phpcore/soap.php" 

script: 
    - phpunit --version
    - phpunit /var/www/src/wp-content/plugins/Wordpress/vendor/splash/phpcore/Tests/Core/C01ClassesTest.php -c build/phpunit.xml.dist
    - phpunit -c build/phpunit.xml.dist

# Tells Travis CI not to run unit tests against the setup branch
branches:
    except:
        - setup
        
        
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always
