# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# Versions of PHP to test against
php:
    - "5.6"
    - "7.0"
    - "7.1"

# Specify versions of WordPress to test against
# WP_VERSION = WordPress version number (use "master" for SVN trunk)
# WP_MULTISITE = whether to test multisite (use either "0" or "1")
env:
    - WP_VERSION=master WP_MULTISITE=0
    - WP_VERSION=4.8.1 WP_MULTISITE=0
    - WP_VERSION=master WP_MULTISITE=1
    - WP_VERSION=4.8.1 WP_MULTISITE=1

before_script:
    # Grab the setup script and execute
    - wget https://raw.github.com/tierra/wordpress-plugin-tests/setup/setup.sh
    - source setup.sh
    # Run Composer
    - composer install    

script: 
    - phpunit --version
    - phpunit /tmp/wordpress/wp-content/plugins/Wordpress/vendor/splash/phpcore/Tests/Core/C01ClassesTest.php

# wordpress-plugin-tests specific config
# Tells Travis CI not to run unit tests against the setup branch
branches:
    except:
        - setup
