# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# Versions of PHP to test against
php:
#    - "5.6"
    - "7.0"
#    - "7.1"

# Specify versions of WordPress to test against
# WP_VERSION = WordPress version number (use "master" for SVN trunk)
# WP_MULTISITE = whether to test multisite (use either "0" or "1")
env:
    - WP_VERSION=master WP_MULTISITE=0
 #   - WP_VERSION=4.8.1 WP_MULTISITE=0
 #   - WP_VERSION=master WP_MULTISITE=1
 #   - WP_VERSION=4.8.1 WP_MULTISITE=1
    
install:
    
#    # Install Apache web server and FastCGI module ...
#    - sudo apt-get install apache2 libapache2-mod-fastcgi > /dev/null
#    # Enable PHP-FPM and FastCGI ...
#    - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf; fi
#    - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
#    - sudo a2enmod rewrite actions fastcgi alias
#    - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
#    - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm  
#    # Configure application's virtual host ...
#    - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
#    # Disable Xdebug ...
#    - phpenv config-rm xdebug.ini
#    # Enable Mod_rewrite
#    - sudo a2enmod rewrite
#    # Restart Apache
#    - sudo service apache2 restart
    # Prepare Web folder
#    - sudo chmod 777 /var/www -Rf
#    - sudo rm -rf /var/www/*
  
before_script:
  
    - export PLUGIN_SLUG=$(basename $(pwd))
    
    # Clone Wordpress & Move to Web folder
    - git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/Wordpress
    
    # Install WooCommerce Module
    - git clone --depth=1 https://github.com/woocommerce/woocommerce.git /tmp/Wordpress/src/wp-content/plugins/woocommerce
    
    # Copy Splash Module to Wordpress folder

    - mv "$PLUGIN_SLUG" "/tmp/Wordpress/src/wp-content/plugins/splash-connector"

    # Configure Wordpress
    - cd /tmp/Wordpress
    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    - cp wp-tests-config-sample.php wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
    - sed -i "s/yourusernamehere/travis/" wp-tests-config.php
    - sed -i "s/yourpasswordhere//" wp-tests-config.php
    
    # Disable Wp Debug (Not to Show notice etc...) 
    - sed -i "s/WP_DEBUG/WP_NO_DEBUG/" wp-tests-config.php
    
#    - sudo chmod 777 -Rf /var/www
#    - sudo chown www-data:www-data -Rf /var/www
    
    # Move to Splash Plugin Dir
    - cd "/tmp/Wordpress/src/wp-content/plugins/splash-connector"
    
    # Run Composer
    - composer update 

script: 
    - phpunit --version
    - phpunit -c build/phpunit.xml.dist 
#    - phpunit -c build/phpunit.xml.dist /var/www/src/wp-content/plugins/splash-connector/vendor/splash/phpcore/Tests/

# Tells Travis CI not to run unit tests against the setup branch
branches:
    except:
        - setup
        
        
notifications:
  email:         
    on_success: never # default: change
    on_failure: never # default: always

after_failure:

#    - curl -sL -w "%{http_code}\\n" "http://travis/src/readme.html" 
#    - curl -sL -w "%{http_code}\\n" "http://travis/src/wp-content/plugins/splash-connector/vendor/splash/phpcore/soap.php" 
#    - sudo cat /var/log/apache2/error.log
#    - sudo cat /etc/apache2/ports.conf
#    - sudo cat /var/log/apache2/access.log
    